# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1329930989);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1329931049);
user_pref("extensions.enabledItems", "{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.1.19");
user_pref("extensions.lastAppVersion", "3.1.19");
user_pref("intl.charsetmenu.mailview.cache", "ISO-8859-1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.account2.server", "server2");
user_pref("mail.accountmanager.accounts", "account2,account1");
user_pref("mail.accountmanager.defaultaccount", "account2");
user_pref("mail.accountmanager.localfoldersserver", "server2");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.identity.id1.archive_folder", "imap://dfitzwell%40mail.titleloanplace.com@mail.tmxcredit.net/[Gmail]/All Mail");
user_pref("mail.identity.id1.archives_folder_picker_mode", "1");
user_pref("mail.identity.id1.draft_folder", "imap://dfitzwell%40mail.titleloanplace.com@mail.tmxcredit.net/Drafts");
user_pref("mail.identity.id1.drafts_folder_picker_mode", "0");
user_pref("mail.identity.id1.fcc_folder", "imap://dfitzwell%40mail.titleloanplace.com@mail.tmxcredit.net/Sent");
user_pref("mail.identity.id1.fcc_folder_picker_mode", "0");
user_pref("mail.identity.id1.fullName", "Dick Fitzwell");
user_pref("mail.identity.id1.smtpServer", "smtp2");
user_pref("mail.identity.id1.stationery_folder", "imap://dfitzwell%40mail.titleloanplace.com@mail.tmxcredit.net/Templates");
user_pref("mail.identity.id1.tmpl_folder_picker_mode", "0");
user_pref("mail.identity.id1.useremail", "dfitzwell@mail.titleloanplace.com");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.root.imap", "/home/dfitzwell/.icedove/bcf7af58.default/ImapMail");
user_pref("mail.root.imap-rel", "[ProfD]ImapMail");
user_pref("mail.root.none", "/home/dfitzwell/.icedove/bcf7af58.default/Mail");
user_pref("mail.root.none-rel", "[ProfD]Mail");
user_pref("mail.server.server1.capability", 403448357);
user_pref("mail.server.server1.check_new_mail", true);
user_pref("mail.server.server1.directory", "/home/dfitzwell/.icedove/bcf7af58.default/ImapMail/mail.tmxcredit.net");
user_pref("mail.server.server1.directory-rel", "[ProfD]ImapMail/mail.tmxcredit.net");
user_pref("mail.server.server1.hostname", "mail.tmxcredit.net");
user_pref("mail.server.server1.is_gmail", true);
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.max_cached_connections", 5);
user_pref("mail.server.server1.name", "dfitzwell@mail.titleloanplace.com");
user_pref("mail.server.server1.namespace.personal", "\"\"");
user_pref("mail.server.server1.port", 993);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.timeout", 29);
user_pref("mail.server.server1.type", "imap");
user_pref("mail.server.server1.userName", "dfitzwell@mail.titleloanplace.com");
user_pref("mail.server.server2.directory", "/home/dfitzwell/.icedove/bcf7af58.default/Mail/Local Folders");
user_pref("mail.server.server2.directory-rel", "[ProfD]Mail/Local Folders");
user_pref("mail.server.server2.hostname", "Local Folders");
user_pref("mail.server.server2.login_at_startup", true);
user_pref("mail.server.server2.name", "Local Folders");
user_pref("mail.server.server2.type", "none");
user_pref("mail.server.server2.userName", "nobody");
user_pref("mail.smtp.defaultserver", "smtp2");
user_pref("mail.smtpserver.smtp2.authMethod", 3);
user_pref("mail.smtpserver.smtp2.description", "TMX");
user_pref("mail.smtpserver.smtp2.hostname", "mail.tmxcredit.net");
user_pref("mail.smtpserver.smtp2.port", 465);
user_pref("mail.smtpserver.smtp2.try_ssl", 3);
user_pref("mail.smtpserver.smtp2.username", "dfitzwell@mail.titleloanplace.com");
user_pref("mail.smtpservers", "smtp2");
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "3.1.19");
user_pref("mailnews.tags..color", "#FF0000");
user_pref("mailnews.tags..tag", "Important");
user_pref("mailnews.tags..color", "#FF9900");
user_pref("mailnews.tags..tag", "Work");
user_pref("mailnews.tags..color", "#009900");
user_pref("mailnews.tags..tag", "Personal");
user_pref("mailnews.tags..color", "#3333FF");
user_pref("mailnews.tags..tag", "To Do");
user_pref("mailnews.tags..color", "#993399");
user_pref("mailnews.tags..tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
