- op: replace
  path: "/metadata/name"
  value: "abcd-foo-forwarder"
- op: replace
  path: "/metadata/namespace"
  value: "nginx-internal"
- op: replace
  path: "/spec/ingressClassName"
  value: "nginx-internal"
- op: replace
  path: "/spec/rules/0/host"
  value: "abcd.foo.com"
- op: replace
  path: "/spec/rules/0/http/paths/0/backend/service/name"
  value: "abcd-foo"
- op: replace
  path: "/spec/rules/0/http/paths/0/backend/service/port/number"
  value: 443
- op: replace
  path: "/spec/tls/0/hosts/0"
  value: "abcd.foo.com"
- op: replace
  path: "/spec/tls/0/secretName"
  value: "tls-abcd-foo-crt"
- op: add
  path: "/metadata/annotations/nginx.ingress.kubernetes.io~1upstream-vhost"
  value: "abcd-internal.foo.com"
